import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-4 md:px-24 overflow-x-hidden relative">
        {/* circle colour element */}
        <div className="h-80 w-80 absolute -top-36 -left-32 md:-top-20 md:-left-28 -z-10 bg-pink-200 rounded-full blur-2xl"></div>
        {/* circle colour element */}
        <div className="h-56 w-56 md:h-80 md:w-80 absolute top-[64rem] right-0 md:top-[48rem] md:-bottom-[30rem] md:-right-36 -z-10 bg-purple-200 rounded-full blur-2xl"></div>
        {children}
      </body>
    </html>
  );
}
